---
    deployment:
        tasks:
            - export DEPLOYPATH=/home/bgitbrentynnet/public_html/
            - /bin/cp -R .output/public/_nuxt $DEPLOYPATH
            - /bin/cp -R .output/public/about $DEPLOYPATH
            - /bin/cp -R .output/public/assets $DEPLOYPATH
            - /bin/cp -R .output/public/contact $DEPLOYPATH
            - /bin/cp -R .output/public/icons $DEPLOYPATH
            - /bin/cp -R .output/public/screenshots $DEPLOYPATH
            - /bin/cp -R .output/public/skills $DEPLOYPATH
            - /bin/cp .output/public/200.html $DEPLOYPATH
            - /bin/cp .output/public/404.html $DEPLOYPATH
            - /bin/cp .output/public/favicon.ico $DEPLOYPATH
            - /bin/cp .output/public/index.html $DEPLOYPATH
            - /bin/cp .output/public/license.txt $DEPLOYPATH
            - /bin/cp .output/public/robots.txt $DEPLOYPATH
            - /bin/cp .output/public/sitemap.txt $DEPLOYPATH